### Create category
POST localhost:8080/category
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMjgwMDk3OCwiZXhwIjoxNzMyODg3Mzc4fQ.YzU82lRfX8ZEBKwX95dAy0xEi6Xi0TWXTELhncwfgHw
Content-Type: application/json

{
  "name": "BBB"
}