### Create channel (RoleUser)
POST localhost:8080/channel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI3MjExMDcsImV4cCI6MTczMjgwNzUwN30.DAzc0JxmfL5x3nQW995YwEar9aDobWU9Gi7sFkR2bnk
#admin##Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMjcyMjA4MywiZXhwIjoxNzMyODA4NDgzfQ.O1snDQ31F2bRazAKVfNKaNegtfnuH8QyTClwit6-G1s

{
  "name": "odilov",
  "description": "zo'r kanal bu qoling chiqib ketmang",
  "bannerId": "35950f14-a106-42a2-a32b-a9618b8da610.jpg",
  "photoId": "35950f14-a106-42a2-a32b-a9618b8da610.jpg"

}

### Update photo of chanel
PUT localhost:8080/channel/update/photo/c1aafcbd-4f5a-4386-88ce-c640bee187af?photoId=9745f793-c6ca-4349-ba71-d2e37d699848.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzIzNjY4OTEsImV4cCI6MTczMjQ1MzI5MX0.JkqjXnTL6uDAQjXIHkD30Vnnlz6xn_gHEFxOWpIe6CI

### Update banner of chanel
PUT localhost:8080/channel/update/banner/c1aafcbd-4f5a-4386-88ce-c640bee187af?bannerId=9745f793-c6ca-4349-ba71-d2e37d699848.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzIzNjY4OTEsImV4cCI6MTczMjQ1MzI5MX0.JkqjXnTL6uDAQjXIHkD30Vnnlz6xn_gHEFxOWpIe6CI

### Update info of chanel
PUT localhost:8080/channel/update/chanel-info/c1aafcbd-4f5a-4386-88ce-c640bee187af
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzIzNjY4OTEsImV4cCI6MTczMjQ1MzI5MX0.JkqjXnTL6uDAQjXIHkD30Vnnlz6xn_gHEFxOWpIe6CI

{
  "name": "rahmatullosblog",
  "description": "zo'r bola"
}

### Get all by pagination
GET localhost:8080/channel/pagination?page=1&size=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMjcyMjA4MywiZXhwIjoxNzMyODA4NDgzfQ.O1snDQ31F2bRazAKVfNKaNegtfnuH8QyTClwit6-G1s
##USER##Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI3MjExMDcsImV4cCI6MTczMjgwNzUwN30.DAzc0JxmfL5x3nQW995YwEar9aDobWU9Gi7sFkR2bnk
### Get by id
GET localhost:8080/channel/by/307bb48b-c0d8-4b1b-bd4e-390bcca15dd0

### Update info of chanel
PUT localhost:8080/channel/change-status/3d3905cd-05b4-43e1-b211-c5b61993b4f2?status=BLOCK
Content-Type: application/json

### Get channel List of user
GET localhost:8080/channel/users-channel
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI1Mjk1NzIsImV4cCI6MTczMjYxNTk3Mn0.jECNxc8UxfvbigXosyrbuIAai-mDcu9izXYcq7cPsfY
