### create comment
POST localhost:8080/comment
#user1Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI5NTk3NDgsImV4cCI6MTczMzA0NjE0OH0.a_LH5u7Z2VP9SoeUM-EAj9MrhVvy49kVIetOPg1lcak
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoib2RpbG92cmFobWF0dWxsbzRAZ21haWwuY29tIiwiaWF0IjoxNzMyOTYxOTkyLCJleHAiOjE3MzMwNDgzOTJ9.XSXR-uf8mPdcKRTLgwaAW1Wp8ytu4Lpl-wk2R62RtMg
#admin###Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMjk1OTY4OSwiZXhwIjoxNzMzMDQ2MDg5fQ.fWjxRGzsuzqcbSHazjhivVe4qyh6Ei6Y_9TTnSZoHk0
Content-Type: application/json

{
  "content": "bfekrbe ",
  "videoId": "530e73e1-152c-4bb7-8d48-a9951a0d385e.mp4"

}

### update comment
PUT localhost:8080/comment/4
#fakeuser Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI5NTk3NDgsImV4cCI6MTczMzA0NjE0OH0.a_LH5u7Z2VP9SoeUM-EAj9MrhVvy49kVIetOPg1lcak
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoib2RpbG92cmFobWF0dWxsbzRAZ21haWwuY29tIiwiaWF0IjoxNzMyOTYxOTkyLCJleHAiOjE3MzMwNDgzOTJ9.XSXR-uf8mPdcKRTLgwaAW1Wp8ytu4Lpl-wk2R62RtMg
#admin Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMjk1OTY4OSwiZXhwIjoxNzMzMDQ2MDg5fQ.fWjxRGzsuzqcbSHazjhivVe4qyh6Ei6Y_9TTnSZoHk0
Content-Type: application/json

{
  "content": "da nimasini etasan jigar",
  "videoId": "530e73e1-152c-4bb7-8d48-a9951a0d385e.mp4"
}

### delete comment
PUT localhost:8080/comment/delete/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoib2RpbG92cmFobWF0dWxsbzRAZ21haWwuY29tIiwiaWF0IjoxNzMyOTYxOTkyLCJleHAiOjE3MzMwNDgzOTJ9.XSXR-uf8mPdcKRTLgwaAW1Wp8ytu4Lpl-wk2R62RtMg

### Get all comments
GET localhost:8080/comment/all?page=1&size=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMjk1OTY4OSwiZXhwIjoxNzMzMDQ2MDg5fQ.fWjxRGzsuzqcbSHazjhivVe4qyh6Ei6Y_9TTnSZoHk0

### GET by profile Id (only ADMIN)
GET localhost:8080/comment/by-profile/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMzA2Nzk4NCwiZXhwIjoxNzMzMTU0Mzg0fQ.DfIEoKkAWVoe-qDRqAjTNJOCtH_dJi8pNHwv0HW1PeA

### Get by own profile id
GET localhost:8080/comment/by-own-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzMxMjI5NDUsImV4cCI6MTczMzIwOTM0NX0.wXlhOpY60rVwbRKSKl-KHAApjIl_c58elCV2F-KIYms

### Get Comment List of video by videoId
GET localhost:8080/comment/by-video/530e73e1-152c-4bb7-8d48-a9951a0d385e.mp4

### Getting reply comments of comment
GET localhost:8080/comment/by-comment/1