### create video
POST localhost:8080/video
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI1Mjk1NzIsImV4cCI6MTczMjYxNTk3Mn0.jECNxc8UxfvbigXosyrbuIAai-mDcu9izXYcq7cPsfY
Content-Type: application/json

{
  "id": "530e73e1-152c-4bb7-8d48-a9951a0d385e.mp4",
  "title": "Kutubxonadan lavha",
  "description": "Kutubxonada deadline uchun olingan video",
  "attachId": "35950f14-a106-42a2-a32b-a9618b8da610.jpg",
  "previewAttachId": "9745f793-c6ca-4349-ba71-d2e37d699848.jpg",
  "categoryId": 1,
  "channelId": "d6142e7c-7876-455d-b4c8-a3e916b31711",
  "videoType": "SHORT",
  "videoStatus": "PRIVATE"
}

### update video
PUT localhost:8080/video/530e73e1-152c-4bb7-8d48-a9951a0d385e.mp4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI1Mjk1NzIsImV4cCI6MTczMjYxNTk3Mn0.jECNxc8UxfvbigXosyrbuIAai-mDcu9izXYcq7cPsfY
Content-Type: application/json

{
  "title": "library",
  "description": "I am in library",
  "videoStatus": "PUBLIC"
}

### Change video status
PUT localhost:8080/video/status/530e73e1-152c-4bb7-8d48-a9951a0d385e.mp4?status=PRIVATE
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic3ViIjoidXNlckBnbWFpbC5jb20iLCJpYXQiOjE3MzI1Mjk1NzIsImV4cCI6MTczMjYxNTk3Mn0.jECNxc8UxfvbigXosyrbuIAai-mDcu9izXYcq7cPsfY

### Increase viewCount
PUT localhost:8080/video/view-count/530e73e1-152c-4bb7-8d48-a9951a0d385e.mp4

### Get pagination by categoryId
GET localhost:8080/video/byCategory/1

### GET by title
GET localhost:8080/video/title/kutubxona

### GET by TagId
GET localhost:8080/video/tag/2?page=1&size=2

### Get all
GET localhost:8080/video/all?page=1&size=5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTczMjcyMjA4MywiZXhwIjoxNzMyODA4NDgzfQ.O1snDQ31F2bRazAKVfNKaNegtfnuH8QyTClwit6-G1s